config/routes.rb
Rails.application.routes.draw do
  # Root path (homepage)
  root 'home#index'

  # User authentication routes
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  post 'users/:id/add_payment_method', to: 'users#add_payment_method', as: 'add_payment_method_user'
  post 'users/:id/add_address', to: 'users#add_address', as: 'add_address_user'

  # User routes for new, create, show, edit, update

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      delete 'delete_address', to: 'users#delete_address'
      delete 'delete_payment_method', to: 'users#delete_payment_method'
    end
  end
  get '/profile/:id', to: 'users#show', as: 'profile'


  # Item routes for creating, showing, editing, updating, and deleting item listings
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
  get 'sell', to: 'items#new'
  get 'item', to: 'items#show'

  # FAQ route for showing the FAQ page
  get 'faq', to: 'faq#show', as: 'faq'

  # Checkout route for showing the checkout page
  #get 'checkout/:item_id', to: 'checkout#show', as: 'checkout_show'
  # Set up to handle the purchase of an item
  #post 'checkout/:id/purchase', to: 'checkout#purchase', as: 'checkout_purchase'

  resources :checkout, only: [:show] do
    member do
      post 'purchase'
    end
  end


  # Search route for searching items with optional category filtering
  get 'search', to: 'search#index'

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:create, :destroy]

  resources :bookmarks, only: [:create, :destroy]

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :require_login
  before_action :set_item, only: [:show, :purchase]

  def show
    @user = current_user
    @seller = User.find(@item.user_id)
  end


  def purchase
    # No need to find @item again, it's already set by set_item
    result = current_user.purchase_item(@item, params[:address_id], params[:payment_method_id])

    if result[:success]
      redirect_to root_path, notice: result[:message]
    else
      redirect_to root_path, alert: result[:message]
    end
  end
end

app/views/checkout/show.html.haml
= form_tag purchase_checkout_path(@item), method: :post do
  .checkout-container
    %h1 Checkout

    .checkout-item
      .item-details
        %h2= @item.title
        %p.seller Buyer: #{@user.username}
        %p.seller Seller: #{@seller.username}
        - if @item.images.any?
          = image_tag @item.images.first.data_uri, alt: @item.title, class: 'item-image'
        %p= @item.description
        %p.item-price
          %h2.current-price= "Total: $#{'%.2f' % @item.price}"

    .address-selection
      %label{for: "address-select"} Select Shipping Address:
      %select#address-select{name: "address_id"}
        %option{value: nil} Choose an address
        - @user.addresses.each do |address|
          %option{value: address.id}= "#{address.shipping_address_1}, #{address.city}, #{address.state}"

    .payment-selection
      %label{for: "payment-method-select"} Select a Payment Method:
      %select#payment-method-select{name: "payment_method_id"}
        %option{value: nil} Choose a payment method
        - @user.payment_methods.each do |payment_method|
          %option{value: payment_method.id}= "Card ending in #{payment_method.card_number[-4..-1]}"

    = link_to "Add Payment", edit_user_path(@user), class: 'checkout-edit-profile-button'

    - if @item.purchased?
      %p This item has already been purchased.
      = link_to 'Back', item_path(@item), class: "back-button"
    - else
      = submit_tag 'Confirm and pay', class: "confirm-button"
      = link_to 'Back', item_path(@item), class: "back-button"