config/routes.rb
Rails.application.routes.draw do
  # Root path (homepage)
  root 'home#index'

  # User authentication routes
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  post 'users/:id/add_payment_method', to: 'users#add_payment_method', as: 'add_payment_method_user'
  post 'users/:id/add_address', to: 'users#add_address', as: 'add_address_user'

  # User routes for new, create, show, edit, update

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      delete 'delete_address', to: 'users#delete_address'
      delete 'delete_payment_method', to: 'users#delete_payment_method'
    end
  end
  get '/profile/:id', to: 'users#show', as: 'profile'


  # Item routes for creating, showing, editing, updating, and deleting item listings
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
  get 'sell', to: 'items#new'
  get 'item', to: 'items#show'

  # FAQ route for showing the FAQ page
  get 'faq', to: 'faq#show', as: 'faq'

  # Checkout route for showing the checkout page
  #get 'checkout/:item_id', to: 'checkout#show', as: 'checkout_show'
  # Set up to handle the purchase of an item
  #post 'checkout/:id/purchase', to: 'checkout#purchase', as: 'checkout_purchase'

  resources :checkout, only: [:show] do
    member do
      post 'purchase'
    end
  end


  # Search route for searching items with optional category filtering
  get 'search', to: 'search#index'

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:create, :destroy]

  resources :bookmarks, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  before_save :create_session_token
  # Associations
  has_many :items, dependent: :delete_all
  has_many :addresses, dependent: :delete_all
  has_many :payment_methods, dependent: :delete_all
  has_many :bookmarks, dependent: :delete_all
  has_many :bookmarked_items, through: :bookmarks, source: :item, dependent: :delete_all
  has_many :purchases, dependent: :delete_all
  has_many :purchased_items, through: :purchases, source: :item, dependent: :delete_all
  has_many :reviews, dependent: :delete_all

  has_many :written_reviews, class_name: 'Review', foreign_key: 'reviewer_id', dependent: :destroy
  has_many :received_reviews, class_name: 'Review', foreign_key: 'seller_id', dependent: :destroy

  before_save { self.username = username.downcase }

  # Validations
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def self.create_with_omniauth(auth)
    create!(
      provider: auth['provider'],
      uid: auth['uid'],
      username: auth['info']['name'],
      email: auth['info']['email'],
    )
  end

  def create_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def add_bookmark(item_id)
    item = Item.find_by(id: item_id)
    unless bookmarked_items.include?(item)
      bookmarked_items << item
    end
  end

  def remove_bookmark(item_id)
    item = Item.find_by(id: item_id)
    if bookmarked_items.include?(item)
      bookmarked_items.delete(item)
    else
      false
    end
  end

  def bookmarked(item)
    bookmarked_items.include?(item)
  end

  def get_users_suggested_items
    # Select bookmarked items that have not been purchased
    suggested_items = bookmarked_items.includes(:purchase).where(purchases: { item_id: nil }).limit(4)
    num_items = suggested_items.length

    # If there are less than 4 bookmarked items, fill the rest with other items that have not been purchased
    if num_items < 4
      excluded_item_ids = suggested_items.map(&:id)
      additional_items = Item.includes(:purchase)
                             .where.not(user: self)
                              .where.not(id: excluded_item_ids)
                             .where(purchases: { item_id: nil })
                             .limit(4 - num_items)
      suggested_items += additional_items
    end
    suggested_items
  end

  def self.get_suggested_items
    Item.includes(:purchase).where(purchases: { item_id: nil }).limit(4)
  end

  def purchase_item(item, address_id, payment_method_id)
    return { success: false, message: 'Item not found.' } unless item

    if item.purchase.present?
      { success: false, message: 'This item has already been purchased.' }
    else
      purchase = purchases.create(item: item, address_id: address_id, payment_method_id: payment_method_id)
      if purchase.persisted?
        { success: true, message: 'Purchase successful!' }
      else
        { success: false, message: "Purchase Unsuccessful!\n" + purchase.errors.full_messages.join("\n") }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_current_user, :only => [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_filter :find_user, :only => [:show, :edit]

  # Show User Profile
  def show
    @user = User.find(params[:id])
    @reviews = @user.received_reviews.take(15)
  end

  # Edit User Profile
  def edit
    @user = current_user
  end

  # Update User Profile


  def add_payment_method
    @user = current_user

    payment_method = PaymentMethod.new

    today = Date.today

    if params[:expiration_year].to_i < today.year
      flash[:error] = "Invalid Expiration Date"
      redirect_to edit_user_path(current_user)
      return
    elsif params[:expiration_year].to_i == today.year && params[:expiration_month].to_i <= today.month
      flash[:error] = "Invalid Expiration Date"
      redirect_to edit_user_path(current_user)
      return
    end

    expiration_date = params[:expiration_month] + '/' + params[:expiration_year]

    if payment_method.valid_payment_method_input?(params[:card_number], expiration_date)
      @user.payment_methods.create!(card_number: params[:card_number], expiration_date: expiration_date)
      flash[:notice] = "Payment Method Added"
    else
      flash[:error] = "Invalid Payment Method Inputs: 15, 16, or 19 digit card number, 3 digit cvv, and (MM/YYYY) expiration date"
    end

    redirect_to edit_user_path(current_user)
  end

  def add_address
    @user = current_user

    input_check = Address.new

    if params[:country] == "Select Country"
      flash[:error] = "Invalid Address Inputs"
      redirect_to user_path(@user)
      return
    elsif params[:country] == "United States" && params[:state] == "Select State"
      flash[:error] = "Invalid Address Inputs"
      redirect_to user_path(@user)
      return
    end

    if params[:state] == "Select State"
      params[:state] = ""
    end

    if input_check.valid_address_input?(params[:shipping_address_1], params[:shipping_address_2], params[:city], params[:state], params[:country], params[:postal_code])
      @user.addresses.create!(shipping_address_1: params[:shipping_address_1], shipping_address_2: params[:shipping_address_2], city: params[:city], state: params[:state], country: params[:country], postal_code: params[:postal_code])
      flash[:notice] = "Address Added"
    else
      flash[:error] = "Invalid Address Inputs"
    end
    redirect_to edit_user_path(current_user)
  end

  def delete_address

    if params[:address_id].blank?
      redirect_to edit_user_path(current_user), alert: 'Could not delete the address. Must select an address.'
    else
      address = current_user.addresses.find(params[:address_id])
      if address.destroy
        redirect_to edit_user_path(current_user), notice: 'Address deleted successfully.'
      else
        redirect_to edit_user_path(current_user), alert: 'Could not delete the address.'
      end
    end



  end

  def delete_payment_method
    if params[:payment_method_id].blank?
      redirect_to edit_user_path(current_user), alert: 'Could not delete the payment method. Must select a payment method.'

    else
      payment_method = current_user.payment_methods.find(params[:payment_method_id])

      if payment_method.destroy
        redirect_to edit_user_path(current_user), notice: 'Payment method deleted successfully.'
      else
        redirect_to edit_user_path(current_user), alert: 'Could not delete the payment method.'
      end

    end

  end
end

app/views/users/edit.html.haml
-# in app/views/users/edit.html.haml
- flash.each do |type, message|
  %div{ class: "flash #{type}" }= message

- countries_list = [ "Select a Country", "United States of America", "Afghanistan",
  "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina",
  "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
  "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
  "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
  "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada",
  "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros",
  "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica",
  "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti",
  "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador",
  "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji",
  "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece",
  "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
  "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
  "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo",
  "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
  "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia",
  "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
  "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique",
  "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua",
  "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan",
  "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
  "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
  "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
  "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan",
  "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania",
  "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
  "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela",
  "Vietnam", "Yemen", "Zambia", "Zimbabwe"];

- states_list = [ "Select a State", "Alabama", "Alaska", "Arizona", "Arkansas", "California",
  "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois",
  "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
  "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
  "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota",
  "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin",
  "Wyoming"];

.edit-profile-container
  .edit-profile-header
    %h1 Edit Profile
    %h2 Add Payment Method
  = form_tag add_payment_method_user_path(current_user), method: :post, class: 'user-form' do
    .payment-fields
      = label_tag :card_number, "Card number #{content_tag(:span, '*', class: 'required')}".html_safe
      = text_field_tag :card_number, nil, maxlength: '19', placeholder: 'XXXX XXXX XXXX XXXX', class: 'card-number-input', autocomplete: 'cc-number', required: true, pattern: "\\d{4} \\d{4} \\d{4} \\d{4}"

      = label_tag :expiration_date, "Expiration Date #{content_tag(:span, '*', class: 'required')}".html_safe
      %div.expiration-date-container
        = select_tag :expiration_month, options_for_select((1..12).map { |m| m < 10 ? "0#{m}" : m.to_s }, include_blank: true), required: true, class: 'expiration-date-part'
        %span.slash /
        = select_tag :expiration_year, options_for_select((Time.now.year..(Time.now.year+10)).to_a, include_blank: true), required: true, class: 'expiration-date-part'
    = submit_tag 'Add Payment Method'
  %h2 Add Shipping Address
  = form_tag add_address_user_path(current_user), method: :post, class: 'user-form' do
    .address-fields
      = label_tag :shipping_address_1, "Shipping Address 1 #{content_tag(:span, '*', class: 'required')}".html_safe
      = text_field_tag 'shipping_address_1'
      = label_tag 'Shipping Address 2'
      = text_field_tag 'shipping_address_2'
      = label_tag :country, "Country #{content_tag(:span, '*', class: 'required')}".html_safe
      = select_tag 'country', options_for_select(countries_list), id: 'country'
      #state-select
        = label_tag 'State'
        = select_tag 'state', options_for_select(states_list), id: 'state'
      = label_tag :city, "City #{content_tag(:span, '*', class: 'required')}".html_safe
      = text_field_tag 'city'
      = label_tag :postal_code, "Postal Code #{content_tag(:span, '*', class: 'required')}".html_safe
      = text_field_tag 'postal_code'
    = submit_tag 'Add Address'
  -# Form for deleting an address
  %h2 Delete Shipping Address
  = form_tag delete_address_user_path, method: :delete, class: 'user-form' do
    .address-selection
      %label{for: "address-select"} Select Shipping Address to Delete:
      %select#address-select{name: "address_id"}
        %option{value: nil} Choose an address
        - @user.addresses.each do |address|
          %option{value: address.id}= "#{address.shipping_address_1}, #{address.city}, #{address.state}"
    = submit_tag 'Delete Address', data: { confirm: 'Are you sure you want to delete this address?' }

    -# Form for deleting a payment method
  %h2 Delete Payment Method
  = form_tag delete_payment_method_user_path, method: :delete, class: 'user-form' do
    .payment-method-selection
      %label{for: "payment-method-select"} Select Payment Method to Delete:
      %select#payment-method-select{name: "payment_method_id"}
        %option{value: ""} Choose a payment method
        - @user.payment_methods.each do |payment_method|
          %option{value: payment_method.id}= "Card ending in #{payment_method.card_number.last(4)}"
    = submit_tag 'Delete Payment Method', data: { confirm: 'Are you sure you want to delete this payment method?' }

app/views/users/show.html.haml
-# in app/views/users/show.html.haml

- flash.each do |type, message|
  %div{ class: "flash #{type}" }= message
%div.user-profile-container

  %div.user-account-details
    %h2.user-account-title My Account
    %p.user-username
      %strong Username:
      = @user.username
    %p.user-email
      %strong Email:
      = @user.email
    - if logged_in?
      - if current_user.id == @user.id
        %h3.user-addresses-title Addresses
        %table.user-addresses-table
          %thead
            %tr
              %th Address Line 1
              %th Address Line 2
              %th City
              %th State
              %th Country
              %th Postal Code
          %tbody
            - @user.addresses.each do |address|
              %tr
                %td= address.shipping_address_1
                %td= address.shipping_address_2
                %td= address.city
                %td= address.state
                %td= address.country
                %td= address.postal_code

        %h3.user-payment-methods-title Payment Methods
        %table.user-payment-methods-table
          %thead
            %tr
              %th Card Number
              %th Expiration Date
          %tbody
            - @user.payment_methods.each do |payment_method|
              %tr
                %td= "****-****-****-#{payment_method.last_four_digits}"
                %td= payment_method.expiration_date

    - if !current_user.nil?
      - if current_user.id == @user.id
        %div.user-navigation-and-tables
          %div.user-navigation-section
            = form_tag search_path(seller: @user.username), method: :get do
              = hidden_field_tag :seller, @user.username
              = submit_tag "My Items for Sale", name: nil, class: 'user-button'
            = form_tag search_path, method: :get do
              = hidden_field_tag :user_id, @user.id
              = hidden_field_tag :purchased, true
              = submit_tag "My Purchases", name: nil, class: 'user-button'
            = link_to "FAQ Page", faq_path, class: 'user-button user-nav-button'
            = form_tag edit_user_path(@user), method: :get do
              = submit_tag 'Edit Profile', class: 'user-button'
            = link_to "Bookmarks", search_path(bookmarks: '1'), class: 'user-button-bookmarks'
      - else
        %div.user-navigation-and-tables
          %div.user-navigation-section
            = form_tag search_path(seller: @user.username), method: :get do
              = hidden_field_tag :seller, @user.username
              = submit_tag "Items for Sale", name: nil, class: 'user-button user-nav-button'
            = link_to "FAQ Page", faq_path, class: 'user-button user-nav-button'
    - else
      %div.user-navigation-and-tables
        %div.user-navigation-section
          = form_tag search_path(seller: @user.username), method: :get do
            = hidden_field_tag :seller, @user.username
            = submit_tag "Items for Sale", name: nil, class: 'user-button user-nav-button'
          = link_to "FAQ Page", faq_path, class: 'user-button user-nav-button'

    %section.seller-reviews-container
    %h2 Seller Reviews
    - if @reviews.present?
      .reviews-list
        - @reviews.each do |review|
          .review-card
            %h3.review-title= review.title
            %p.review-user
              %strong Review by:
              = link_to review.purchase.user.username, profile_path(id: review.purchase.user.id)
            %p.review-item
              %strong Item:
              = link_to review.purchase.item.title, item_path(review.purchase.item)
            %p.review-rating Rating:
            .rating-stars
              - review.rating.times do
                %span ★
              - (5 - review.rating).times do
                %span ☆
            %p.review-content= review.content
            %p.review-date= review.created_at.strftime("%B %d, %Y")

            - if review.purchase.user == current_user
              = button_to review_path(review), method: :delete, data: { confirm: 'Are you sure you want to delete this review?' }, class: 'delete-review-button' do
                = hidden_field_tag :item_id, review.purchase.item.id
                = 'Delete'

    - else
      %p No reviews yet for this seller.