config/routes.rb
Rails.application.routes.draw do
  # Root path (homepage)
  root 'home#index'

  # User authentication routes
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  post 'users/:id/add_payment_method', to: 'users#add_payment_method', as: 'add_payment_method_user'
  post 'users/:id/add_address', to: 'users#add_address', as: 'add_address_user'

  # User routes for new, create, show, edit, update

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      delete 'delete_address', to: 'users#delete_address'
      delete 'delete_payment_method', to: 'users#delete_payment_method'
    end
  end
  get '/profile/:id', to: 'users#show', as: 'profile'


  # Item routes for creating, showing, editing, updating, and deleting item listings
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
  get 'sell', to: 'items#new'
  get 'item', to: 'items#show'

  # FAQ route for showing the FAQ page
  get 'faq', to: 'faq#show', as: 'faq'

  # Checkout route for showing the checkout page
  #get 'checkout/:item_id', to: 'checkout#show', as: 'checkout_show'
  # Set up to handle the purchase of an item
  #post 'checkout/:id/purchase', to: 'checkout#purchase', as: 'checkout_purchase'

  resources :checkout, only: [:show] do
    member do
      post 'purchase'
    end
  end


  # Search route for searching items with optional category filtering
  get 'search', to: 'search#index'

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:create, :destroy]

  resources :bookmarks, only: [:create, :destroy]

end

app/models/item.rb
class Item < ApplicationRecord
  before_save :round_dimensions

  # Associations
  belongs_to :user
  has_many :images, dependent: :delete_all
  has_and_belongs_to_many :categories, join_table: :items_categories
  has_many :bookmarks, dependent: :delete_all
  has_one :purchase, dependent: :delete

  # Validations
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000000 }
  validates :user_id, presence: true
  validates :length, numericality: { greater_than: 0, less_than: 1000000 }, allow_nil: true
  validates :width, numericality: { greater_than: 0, less_than: 1000000 }, allow_nil: true
  validates :height, numericality: { greater_than: 0, less_than: 1000000 }, allow_nil: true
  validates :weight, numericality: { greater_than: 0, less_than: 1000000 }, allow_nil: true
  validates :dimension_units, inclusion: { in: %w(in ft cm m) }, allow_nil: true
  validates :weight_units, inclusion: { in: %w(oz lbs g kg) }, allow_nil: true
  validates :condition, presence: true, inclusion: { in: 0..4 }

  def self.dimension_units
    %w(in ft cm m)
  end

  def self.weight_units
    %w(oz lbs g kg)
  end

  def self.conditions
    [
      'New',
      'Like New',
      'Used',
      'Well Used',
      'Poor'
    ]
  end

  def self.search(search_term, category_names)
    items = all

    # Scenario 1: No search term or categories, return all items in random order
    return items.order(Arel.sql('RANDOM()')) if search_term.blank? && category_names.blank?

    # Scenario 2: Categories provided, sort by number of matching categories
    if category_names.present?
      category_ids = Category.where(name: category_names).pluck(:id)
      items = items.joins(:categories).where(categories: { id: category_ids })
      items = items.group('items.id').order(Arel.sql('COUNT(categories.id) DESC'))
    end

    # Scenarios 3 and 4: Search term provided
    if search_term.present?
      # For SQLite, we'll just do a simple LIKE match
      # For PostgreSQL, we could use ILIKE for case-insensitive matching or more complex text search features
      match_condition = Rails.env.production? ? 'ILIKE' : 'LIKE'
      items = items.where("title #{match_condition} :search OR description #{match_condition} :search", search: "%#{search_term}%")

      if category_names.blank?
        # Scenario 3: Only search term is provided, sort by relevance
        items = items.order(Arel.sql('title DESC, description DESC'))
      else
        # Scenario 4: Both search term and categories provided, sort by category match count and then search term match
        items = items.group('items.id').order(Arel.sql('COUNT(categories.id) DESC, title DESC, description DESC'))
      end
    end

    items
  end

  def self.get_users_search_items(current_user, params)
    results = if params[:bookmarks].present? && params[:bookmarks] == '1' && current_user
                current_user.bookmarked_items
              elsif params[:purchased].present? && current_user
                current_user.purchased_items
              elsif params[:categories].present? && params[:search_term].present?
                Item.search(params[:search_term], params[:categories])
              elsif params[:categories].present?
                Item.search(nil, params[:categories])
              elsif params[:search_term].present?
                Item.search(params[:search_term], Category.all.map(&:name))
              else
                Item.all
              end

    # unless results.empty? || params[:user_id].present?
    #   results = results.includes(:purchase).where(purchases: { id: nil })
    # end

    if params[:seller].present?
      seller = User.find_by(username: params[:seller])
      results = seller ? results.where("items.user_id = ?", seller.id) : []
      return results if results.empty?
    end

    if params[:min_price].present?
      results = results.where("price >= ?", params[:min_price])
      return results if results.empty?
    end

    if params[:max_price].present?
      results = results.where("price <= ?", params[:max_price])
    end

    results
  end

  def self.get_search_items(params)
    results = if params[:categories].present? && params[:search_term].present?
                Item.search(params[:search_term], params[:categories])
              elsif params[:categories].present?
                Item.search(nil, params[:categories])
              elsif params[:search_term].present?
                Item.search(params[:search_term], Category.all.map(&:name))
              else
                Item.all
              end

    # unless results.empty?
    #   results = results.includes(:purchase).where(purchases: { id: nil })
    # end

    if params[:seller].present?
      seller = User.find_by(username: params[:seller])
      results = seller ? results.where("items.user_id = ?", seller.id) : []
      return results if results.empty?
    end

    if params[:min_price].present?
      results = results.where("price >= ?", params[:min_price])
      return results if results.empty?
    end

    if params[:max_price].present?
      results = results.where("price <= ?", params[:max_price])
    end

    results
  end

  def self.insert_item(user, item_to_insert)
    if item_to_insert[:dimension_units].blank?
      item_to_insert[:dimension_units] = nil
    end
    if item_to_insert[:weight_units].blank?
      item_to_insert[:weight_units] = nil
    end
    item = user.items.create!(
      title: item_to_insert[:title],
      description: item_to_insert[:description],
      price: item_to_insert[:price],
      length: item_to_insert[:length],
      width: item_to_insert[:width],
      height: item_to_insert[:height],
      dimension_units: item_to_insert[:dimension_units],
      weight: item_to_insert[:weight],
      weight_units: item_to_insert[:weight_units],
      condition: item_to_insert[:condition]
    )
    item.add_images(item_to_insert[:images])
    item.add_categories(item_to_insert[:category_ids])

    item
  end

  def add_images(images)
    images.each do |uploaded_image|
      next unless uploaded_image.respond_to?(:tempfile)
      image_file_path = uploaded_image.tempfile.path
      image = MiniMagick::Image.new(image_file_path)
      image.resize('256x256')
      image_type, image_data = Image.get_image_data(image_file_path)
      self.images.create!(data: image_data, image_type: image_type)
    end
  end

  def add_categories(category_ids)
    category_ids.each do |category_id|
      unless category_id.blank?
        self.categories << Category.find(category_id)
      end
    end
  end

  def update_item(item_updates, remove_images)

    # Check that the user is not trying to add more than 5 images
    if check_image_limit(item_updates, remove_images)
      return false
    end


    # Only update attributes that are present
    if item_updates[:dimension_units].blank?
      item_updates[:dimension_units] = nil
    end
    if item_updates[:weight_units].blank?
      item_updates[:weight_units] = nil
    end

    # Update item attributes
    if self.update!(
      title: item_updates[:title],
      description: item_updates[:description],
      price: item_updates[:price],
      length: item_updates[:length],
      width: item_updates[:width],
      height: item_updates[:height],
      dimension_units: item_updates[:dimension_units],
      weight: item_updates[:weight],
      weight_units: item_updates[:weight_units],
      condition: item_updates[:condition]
    )

      # Update categories
      self.add_categories(item_updates[:category_ids])

      if item_updates[:images].present?
        self.add_images(item_updates[:images])
      end

      # Removing images if the user selected to remove any
      if remove_images.present?
        # reverse the keys of the hash since we want to remove the images from last to first to be able to use the index
        remove_images = remove_images.select { |_, value| value == "1" }.keys.map(&:to_i).sort.reverse

        # remove the images from the item
        remove_images.each do |index|
          if index >= 0 && index < self.images.length
            self.images.destroy(self.images[index])
          end
        end
      end
      true
    else
      false
    end
  end

  def find_related_items
    # Fetch other items in the same category
    Item.joins(:categories).where(categories: { id: self.categories.pluck(:id) }).where.not(id: self.id).limit(4)
  end

  # Returns true if the item has been purchased
  def purchased?
    purchase.present?
  end

  def dimensions
    "#{length} x #{width} x #{height} #{dimension_units}"
  end

  def condition_text
    Item.conditions[condition]
  end

  private

  def round_dimensions
    self.length = length.round(1) if length
    self.width = width.round(1) if width
    self.height = height.round(1) if height
    self.weight = weight.round(1) if weight
  end

  def check_image_limit(item_to_update, remove_images)

    # Calculate the total number of images after addition and removal
    total_images = self.images.length
    total_images += item_to_update[:images].length if item_to_update[:images].present?
    total_images -= remove_images.length if remove_images.present?

    # Check if the total exceeds the limit
    total_images > 5
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :set_current_user, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :find_item, only: [:show, :edit, :update, :destroy]
  before_filter :correct_user_for_item, only: [:edit, :update, :destroy]

  # Form for new item
  def new
    @item = Item.new
    @categories = Category.all
  end

  # Create new item listing
  def create
    @item = Item.insert_item(current_user, params[:item])
    redirect_to item_path(@item)
  end

  # Show item details
  def show
    @related_items = @item.find_related_items
    @user = User.find(@item.user_id)
    @bookmarked = current_user.bookmarked_items.include?(@item) if current_user
    @reviews = @user.received_reviews.take(2)
    if @item.purchased?
      render :purchased
    end
  end

  # Edit item form
  def edit
    @categories = Category.all
  end

  # Update item listing
  def update
    # update the item with the new attributes
    if @item.update_item(params[:item], params[:remove_images])
      # set a flash message if the item was updated successfully
      flash[:notice] = "Item updated successfully"
    else
      # set a flash message if the item was not updated successfully
      flash[:error] = "Item could not be updated"
    end

    redirect_to item_path(Item.find(params[:id]))
  end

  # Delete item listing
  def destroy
    if @item.destroy
      flash[:success] = "Item deleted successfully"
    else
      flash[:error] = "Item could not be deleted"
    end
    redirect_to root_path
  end

  def related_items_for(item)
    # Fetch other items by the same user, excluding the current item
    Item.where(user_id: item.user_id).where.not(id: item.id).limit(4)
  end
end

app/views/items/edit.html.haml
-# in app/views/items/edit.html.haml

%div.form-container
  %h1= action_name == 'new' ? 'List a new item' : 'Edit item'
  = form_for @item, html: { multipart: true, class: 'item-form' } do |f|
    - if @item.errors.any?
      #error_explanation
        %h2
          = pluralize(@item.errors.count, "error")
          prohibited this item from being saved:
        %ul
          - @item.errors.full_messages.each do |message|
            %li= message

    .form-field
      = f.label :title
      = f.text_field :title, required: true, maxlength: 255

    .form-field
      = f.label :description
      = f.text_area :description, required: true, maxlength: 1000

    .form-field
      = f.label :width
      = f.number_field :width, required: false, step: '0.01', min: 0

    .form-field
      = f.label :length
      = f.number_field :length, required: false, step: '0.01', min: 0

    .form-field
      = f.label :height
      = f.number_field :height, required: false, step: '0.01', min: 0

    .form-field
      = f.label :dimension_units
      = f.select :dimension_units, Item.dimension_units, {include_blank: true}, required: false

    .form-field
      = f.label :weight
      = f.number_field :weight, required: false, step: '0.01', min: 0

    .form-field
      = f.label :weight_units
      = f.select :weight_units, Item.weight_units, {include_blank: true}, required: false

    .form-field
      = f.label :condition
      = f.select :condition, Item.conditions, {include_blank: true}, required: true

    .form-field
      = f.label :price
      = f.number_field :price, required: true, step: '0.01', min: 0
      #price-breakdown
        %h2#fee-amount Fee (5%): $0.00
        %h2#total-price You Receive: $0.00
      :javascript
        document.addEventListener('DOMContentLoaded', function() {
          function calculateAndDisplay() {
            var price = parseFloat(document.getElementById('item_price').value) || 0;
            var fee = price * 0.05;
            var total = price - fee;
            document.getElementById('fee-amount').textContent = 'Fee (5%): $' + fee.toFixed(2);
            document.getElementById('total-price').textContent = 'You Receive: $' + total.toFixed(2);
          }
          calculateAndDisplay();
          document.getElementById('item_price').addEventListener('input', calculateAndDisplay);
        });
    .form-field
      = f.label :categories
      = f.collection_select :category_ids, @categories, :id, :name, {include_blank: false}, { multiple: true, required: true, size: 3 }

    .form-field
      = f.label :current_images
      - @item.images.each_with_index do |image, index|
        .image-row
          = image_tag image.data_uri, alt: "#{@item.title} image #{index}"
          %label.checkbox-container
            = check_box_tag "remove_images[#{index}]", 1, false, id: "remove_images_#{index}", class: 'custom-checkbox'
            %span Remove image?

    .drop-zone
      %p Drag and drop images here or
      %button#upload-btn{ type: 'button' } Upload New Files (Max: 5 images)
      = f.file_field :images, multiple: true, accept: 'image/*', required: false, style: 'display: none;', id: 'file-input'

    .file-names
      %p#file-list No files selected

    = f.submit action_name == 'new' ? 'List Item' : 'Update Item', class: 'form-submit-button'

app/views/items/new.html.haml
%div.form-container
  %h1= action_name == 'new' ? 'List a new item' : 'Edit item'
  = form_for @item, html: { multipart: true, class: 'item-form' } do |f|
    - if @item.errors.any?
      #error_explanation
        %h2
          = pluralize(@item.errors.count, "error")
          prohibited this item from being saved:
        %ul
          - @item.errors.full_messages.each do |message|
            %li= message

    .form-field
      = f.label :title
      = f.text_field :title, required: true, maxlength: 255

    .form-field
      = f.label :description
      = f.text_area :description, required: true, maxlength: 1000

    .form-field
      = f.label :width
      = f.number_field :width, required: false, step: '0.01', min: 0

    .form-field
      = f.label :length
      = f.number_field :length, required: false, step: '0.01', min: 0

    .form-field
      = f.label :height
      = f.number_field :height, required: false, step: '0.01', min: 0

    .form-field
      = f.label :dimension_units
      = f.select :dimension_units, Item.dimension_units, {include_blank: true}, required: false

    .form-field
      = f.label :weight
      = f.number_field :weight, required: false, step: '0.01', min: 0

    .form-field
      = f.label :weight_units
      = f.select :weight_units, Item.weight_units, {include_blank: true}, required: false

    .form-field
      = f.label :condition
      = f.select :condition, Item.conditions, {include_blank: true}, required: true

    .form-field
      = f.label :price
      = f.number_field :price, required: true, step: '0.01', min: 0
      #price-breakdown
        %h2#fee-amount Fee (5%): $0.00
        %h2#total-price You Receive: $0.00
      :javascript
        document.addEventListener('DOMContentLoaded', function() {
          document.getElementById('item_price').addEventListener('input', function() {
            var price = parseFloat(this.value) || 0;
            var fee = price * 0.05;
            var total = price - fee;
            document.getElementById('fee-amount').textContent = 'Fee (5%): $' + fee.toFixed(2);
            document.getElementById('total-price').textContent = 'You Receive: $' + total.toFixed(2);
          });
        });
    .form-field
      = f.label :categories
      = f.collection_select :category_ids, @categories, :id, :name, {include_blank: false}, { multiple: true, required: true, size: 3 }

    .drop-zone
      %p Drag and drop images here or
      %button#upload-btn{ type: 'button' } Upload Files (Max: 5 images)
      = f.file_field :images, multiple: true, accept: 'image/*', required: true, style: 'display: none;', id: 'file-input'

    .file-names
      %p#file-list No files selected

    = f.submit action_name == 'new' ? 'List Item' : 'Update Item', class: 'form-submit-button'

app/views/items/purchased.html.haml
- flash.each do |type, message|
  %div{ class: "flash #{type}" }= message

%section.item-page

  %h1= @item.title
  %p.item-price= "Price: $#{'%.2f' % @item.price}"

  - if @item.categories.any?
    %p.categories
    %span.label Categories:
    - @item.categories.each do |category|
      = link_to search_path(categories: category[:name]), method: :get, class: 'local-category-button' do
        = category[:name]

  - if @item.images.any?
    .carousel-container
      .carousel-slide
        - @item.images.each_with_index do |image, index|
          = image_tag image.data_uri, alt: "#{@item.title} image #{index}", class: 'item-carousel-image', style: "display: none;"

      %a.carousel-control-prev{ href: "#", onclick: "moveSlide(-1); return false;" }
        %span &laquo; Prev
      %a.carousel-control-next{ href: "#", onclick: "moveSlide(1); return false;" }
        %span Next &raquo;


  .item-action-buttons
    = link_to "View seller's other item's", search_path(seller: @user.username), method: :get, form: {class: 'search-form'}, class: 'search-button'


  .item-details
    %p#item-description= @item.description
    .item-attributes
      %p
        %strong Listed on:
        %span= @item.created_at.strftime("%B %d, %Y")
      %p
        %strong Listed by:
        = link_to @user.username, profile_path(id: @user.id)
      %p
        %strong Purchased by:
        %span= @item.purchase.user.username
      %p
        %strong Purchased on:
        %span= @item.purchase.created_at.strftime("%B %d, %Y")
      - if @item.purchase.user == current_user
        %p
          %strong Delivery Status:
          - if Time.current > @item.purchase.created_at + 1.minute
            %span
              - if @item.purchase.address.nil?
                Delivered
              - else
                Delivered to
                = [@item.purchase.address.shipping_address_1, @item.purchase.address.shipping_address_2].reject(&:blank?).join(', ')
                = [@item.purchase.address.city, @item.purchase.address.state, @item.purchase.address.postal_code].reject(&:blank?).join(', ')
                = @item.purchase.address.country
          -else
            %span
              - if @item.purchase.address.nil?
                En Route
              - else
                En Route to
                = [@item.purchase.address.shipping_address_1, @item.purchase.address.shipping_address_2].reject(&:blank?).join(', ')
                = [@item.purchase.address.city, @item.purchase.address.state, @item.purchase.address.postal_code].reject(&:blank?).join(', ')
                = @item.purchase.address.country


- if @item.purchase.user == current_user and !@item.purchase.reviewed?
  %section.review-form-container
    %h2 Leave a Review for the Seller
    = form_for Review.new, url: reviews_path, html: { class: 'review-form' } do |f|
      = f.hidden_field :item_id, value: @item.id
      = f.hidden_field :reviewer_id, value: @user.id
      = f.hidden_field :seller_id, value: @item.user.id

      .form-group
        = f.label :rating, 'Rating (1 to 5)'
        = f.number_field :rating, in: 1..5, class: 'form-control', required: true

      .form-group
        = f.label :title, 'Review Title'
        = f.text_field :title, class: 'form-control', required: true

      .form-group
        = f.label :content, 'Your Review'
        = f.text_area :content, class: 'form-control', required: true

      = f.submit 'Submit Review', class: 'submit-review-button'
- elsif @item.purchase.user == current_user
%section.seller-reviews-container-2
  %h1 Seller Reviews
  - if @reviews.present?
    .reviews-list-2
      - @reviews.each do |review|
        .review-card
          %h3.review-title= review.title
          %p.review-user
            %strong Review by:
            = link_to review.purchase.user.username, profile_path(id: review.purchase.user.id)
          %p.review-item
            %strong Item:
            = link_to review.purchase.item.title, item_path(review.purchase.item)
            %p.review-rating Rating:
            .rating-stars
              - review.rating.times do
                %span ★
              - (5 - review.rating).times do
                %span ☆
            %p.review-content= review.content
            %p.review-date= review.created_at.strftime("%B %d, %Y")

            - if review.purchase.user == current_user
              = button_to review_path(review), method: :delete, data: { confirm: 'Are you sure you want to delete this review?' }, class: 'delete-review-button' do
                = hidden_field_tag :item_id, review.purchase.item.id
                = 'Delete'
  - else
    %p No reviews yet for this seller.

app/views/items/show.html.haml
- flash.each do |type, message|
  %div{ class: "flash #{type}" }= message

%section.item-page
  .item-and-reviews
    .item-details-container
      %h1= @item.title
      %p.item-price= "Price: $#{'%.2f' % @item.price}"

      - if @item.categories.any?
        %p.categories
          %span.label Categories:
          - @item.categories.each do |category|
            = link_to search_path(categories: category[:name]), method: :get, class: 'local-category-button' do
              = category[:name]

      - if @item.images.any?
        .carousel-container
          .carousel-slide
            - @item.images.each_with_index do |image, index|
              = image_tag image.data_uri, alt: "#{@item.title} image #{index}", class: 'item-carousel-image', style: "display: none;"

          %a.carousel-control-prev{ href: "#", onclick: "moveSlide(-1); return false;" }
            %span &laquo; Prev
          %a.carousel-control-next{ href: "#", onclick: "moveSlide(1); return false;" }
            %span Next &raquo;

      .item-action-buttons
        - if current_user.nil?
          = button_to "Sign in to buy", '/auth/google_oauth2', method: :post, class: 'buy-button'
        - elsif current_user.id == @item.user_id
          = button_to "Edit Item", edit_item_path(id: @item.id), method: :get, class: 'buy-button'
          = button_to "Delete Item", item_path(id: @item.id), method: :delete, data: { confirm: "Are you sure you want to delete this listing?" }, class: 'buy-button'
        - else
          - if @item.purchased?
            %p.item-purchased This item has been purchased
          - else
            = button_to "Buy Now", checkout_path(id: @item.id), method: :get, class: 'buy-button'
        = link_to "View users other item's", search_path(seller: @user.username), method: :get, form: {class: 'search-form'}, class: 'search-button'
        - if logged_in?
          %button#bookmark-button.bookmark-button{ 'data-item-id': @item.id, 'data-bookmarked': @bookmarked ? 1 : 0 }
            = @bookmarked ? 'Unbookmark' : 'Bookmark'
    %section.seller-reviews-container
      %h2 Seller Reviews
      - if @reviews.present?
        .reviews-list
          - @reviews.each do |review|
            .review-card
              %h3.review-title= review.title
              %p.review-user
                %strong Review by:
                = link_to review.purchase.user.username, profile_path(id: review.purchase.user.id)
              %p.review-item
                %strong Item:
                = link_to review.purchase.item.title, item_path(review.purchase.item)
                %p.review-rating Rating:
                .rating-stars
                  - review.rating.times do
                    %span ★
                  - (5 - review.rating).times do
                    %span ☆
              %p.review-content= review.content
              %p.review-date= review.created_at.strftime("%B %d, %Y")

              - if review.purchase.user == current_user
                = button_to review_path(review), method: :delete, data: { confirm: 'Are you sure you want to delete this review?' }, class: 'delete-review-button' do
                  = hidden_field_tag :item_id, review.purchase.item.id
                  = 'Delete'
      - else
        %p No reviews yet for this seller.
  .item-details
    %p#item-description= @item.description
    .item-attributes
      %p
        %strong Size (LxWxH):
        %span= @item.dimensions
      %p
        %strong Weight:
        %span= "#{@item.weight} #{ @item.weight_units }"
      %p
        %strong Condition:
        %span= @item.condition_text
      %p
        %strong Listed on:
        %span= @item.created_at.strftime("%B %d, %Y")
      %p
        %strong Listed by:
        = link_to @user.username, profile_path(id: @user.id)
  %section.related-items
    %h1 You might also like
    - @related_items ||= []
    - @related_items.first(3).each do |item|
      .related-item
        .search-result-item
        = link_to item_path(item), class: 'search-item-link' do
          %figure.search-item-image
            %img{ src: item.images.first.data_uri, alt: item.title }
          .search-item-info
            %h3.search-item-title= item.title
            %p.search-item-price= number_to_currency(item.price)
            %p.search-item-categories
              - item.categories.each_with_index do |category, index|
                = category.name
                - unless index == item.categories.size - 1
                  %span.search-separator ,