config/routes.rb
Rails.application.routes.draw do
  # Root path (homepage)
  root 'home#index'

  # User authentication routes
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  post 'users/:id/add_payment_method', to: 'users#add_payment_method', as: 'add_payment_method_user'
  post 'users/:id/add_address', to: 'users#add_address', as: 'add_address_user'

  # User routes for new, create, show, edit, update

  resources :users, only: [:new, :create, :show, :edit, :update] do
    member do
      delete 'delete_address', to: 'users#delete_address'
      delete 'delete_payment_method', to: 'users#delete_payment_method'
    end
  end
  get '/profile/:id', to: 'users#show', as: 'profile'


  # Item routes for creating, showing, editing, updating, and deleting item listings
  resources :items, only: [:new, :create, :show, :edit, :update, :destroy]
  get 'sell', to: 'items#new'
  get 'item', to: 'items#show'

  # FAQ route for showing the FAQ page
  get 'faq', to: 'faq#show', as: 'faq'

  # Checkout route for showing the checkout page
  #get 'checkout/:item_id', to: 'checkout#show', as: 'checkout_show'
  # Set up to handle the purchase of an item
  #post 'checkout/:id/purchase', to: 'checkout#purchase', as: 'checkout_purchase'

  resources :checkout, only: [:show] do
    member do
      post 'purchase'
    end
  end


  # Search route for searching items with optional category filtering
  get 'search', to: 'search#index'

  resources :categories, only: [:index, :show]

  resources :reviews, only: [:create, :destroy]

  resources :bookmarks, only: [:create, :destroy]

end

app/views/layouts/_header.html.haml
-# app/views/layouts/_header.html.haml

%nav.global-navbar
  .global-container
    = link_to root_path, class: 'global-navbar-brand' do
      = image_tag('logo.png', alt: 'Logo', class: 'global-navbar-logo')
      .text-logo
        %span Deal Docks
    .global-search-bar
      = form_tag search_path, method: :get do
        = text_field_tag :search_term, params[:search_term], placeholder: "Search items...", class: 'global-search-input'
        = submit_tag "Search", class: 'global-search-button'
    - if logged_in?
      = link_to 'Sell Item', sell_path, class: 'global-nav-link'
      = link_to 'Profile', "/profile/#{current_user.id}", class: 'global-nav-link'
      = link_to 'Logout', logout_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'global-nav-link'
    - else
      = link_to 'Login', '/auth/google_oauth2', method: :post, class: 'global-nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Deal Docks
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = favicon_link_tag 'logo.ico'
  %body
    = render 'layouts/header'
    = yield